---
title: "HYCOM-TSIS Post-Particle Tracks"
author: "Sebastian Di Geronimo"
date: 2026-09-09
format: html
editor: source
---

# 1.0 ---- Summary of Document ----

This helps plot the particle tracks afterwards.

# 2.0 ---- Setup ----


## 2.1 Load Libraries

```{r setup, include=FALSE}
if (!nzchar(system.file(package = "librarian"))) 
  install.packages("librarian")

librarian::shelf(
  quiet = TRUE,
  librarian, #conflicted, ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr,
  # forcats, lubridate, glue, fs, 
  fs, magrittr, dplyr, here, ggplot2, lubridate,  stringr, ggnewscale, purrr,
  
  # additional
  # sp, raster, ncdf4,
  sf, terra, metR, tidyterra, geodata,
  marinebon/seascapeR, mapview, lwgeom, writexl
)

# conflicts_prefer(
#   dplyr::filter(), 
#   dplyr::select()
#   )
  
# source aviso functions
source(here("R", "aviso_functions.R"))

path_save <- here("data", "raw", "hycom_particle_tracking")

fs::dir_create(path_save)

```

```{r}
plot_out_path <- here(
  "data", "plots", "hycom_particle_tracker", format(Sys.Date(), "%Y_%m_%d")
  )

dir_create(plot_out_path)

lat_lon <- 
  c(
    # long
    "xmin" = -83.8125,
    "xmax" = -78.3125,
    #lat
    "ymin" = 22.8125,
    "ymax" = 26.4375
  )
```


# Download and Plot Land


```{r country-download}
if (!exists("land_mask")) {
  # Countries for which the shorelines are downloaded and plotted
  countries <- c("USA", "Cuba", "Bahamas")
  
  gd_load <- lapply(
    as.list(countries),
    function(x) {
      gadm <- ""
  
      gadm <- tryCatch(
        geodata::gadm(country = x, level = 0, path = tempdir()),
        error = function(e) NULL
      )
  
      gadm
    }
  )
}
```


```{r country-combine}
if (!exists("land_mask")) {
  
  land_crop <- land_buff <- list()
  base_plt <-
    ggplot() +
    labs(x = NULL, y = NULL) +
    coord_sf(
      xlim = lat_lon[1:2],
      ylim = lat_lon[3:4],
      expand = FALSE
      )  +
    theme_bw()
  
  
  for (i in seq(length(gd_load))) {
    land_crop[[i]] <- crop(gd_load[[i]], ext(lat_lon))
    
    # add land to figure
    base_plt <- base_plt + geom_spatvector(data = land_crop[[i]])
  }
  
  print(base_plt)
}
```

# Create southern Florida Keys National Marine Sanctucary

```{r}
if (FALSE) {
  
  fl_crs <- "EPSG:6442"

  fknms_ply <- seascapeR::get_url_ply(
    "fknms",
    dir_ply = here("data", "raw")
  )
  
  mapviewOptions(basemaps = "Esri.WorldImagery")
  
  split_mutliline <- 
    mapview::mapView(fknms_ply) %>%
    mapedit::editMap()
  
  fknms_ply_prj <- st_transform(fknms_ply, fl_crs) 
  multiline_prj <- 
    st_transform(split_mutliline$finished, fl_crs) %>% 
    st_geometry() %>% 
    st_combine()
  
  plot((multiline_prj))
  
  split_geom <- lwgeom::st_split(
    st_geometry(fknms_ply_prj),
    multiline_prj
    )
  
  split_geom_ply <- 
    split_geom %>% 
    st_as_sf() %>%
    st_collection_extract() %>% 
    st_cast("POLYGON") %>% 
    mutate(
      id = row_number(),
      id = as.character(id)
      ) %>%
  filter(id == "2")

  (split_geom_ply %>% 
    ggplot() +
    geom_sf()) %>% 
    plotly::ggplotly()

  dir_create(here("data", "raw", "fknms_south"))
  st_write(split_geom_ply, here("data", "raw", "fknms_south", "fknms_south.shp"))
  st_write(multiline_prj, here("data", "raw", "fknms_south", "fknms_split_line.shp"))

}
```

# Extract Particles within Florida Keys National Marine Sanctuary

```{r}
fknms_south <- 
  here("data", "raw", "fknms_south") %>% 
  dir_ls(regexp = "fknms_south\\.shp$") %>% 
  st_read() %>% 
  st_transform("EPSG:4326")

base_plt +
  geom_sf(data = fknms_south, fill = NA, color = "red")


particle_track_paths <- 
  here("data", "plots", "hycom_particle_tracker") %>%
  dir_ls() %T>% 
  print() %>% 
  str_subset("2026_08_27") %>% 
  dir_ls(regexp = "particle_tracks") %>% 
  dir_ls() %>% 
  print()

# one cruise plot location
particle_track <- 
  particle_track_paths %>% 
  str_subset("WS17282") %>% 
  readr::read_csv(show_col_types = FALSE)

within_fk_test <- 
  particle_track %>% 
  st_as_sf(coords = c("lon", "lat"), crs = "EPSG:4326") %>% 
  st_filter(
    fknms_south,
    .predicate = st_intersects
  )

base_plt +
  geom_sf(data = fknms_south, fill = NA, color = "red") +
  geom_sf(data = within_fk_test, color = "green")

# ---- #

within_fk <- 
  map(
    particle_track_paths, 
    \(.x) {
      particle_track <- readr::read_csv(.x, show_col_types = FALSE)
      
      within_fk <-
        particle_track %>%
        st_as_sf(coords = c("lon", "lat"), crs = "EPSG:4326") %>%
        st_filter(fknms_south, .predicate = st_intersects)
      }
  )

within_fk_bind <- 
  list_rbind(within_fk, names_to = "cruise") %>% 
  mutate(
    cruise = basename(cruise),
    cruise = str_remove(cruise, "_.*")
    ) %>% 
  st_as_sf()

plt_within <- 
  (base_plt +
  geom_sf(data = fknms_south, fill = NA, color = "red") +
  geom_sf(data = within_fk_bind, aes(color = as.character(part_num), group = cruise),
          size = rel(0.5)) +
  labs(
    shape = "Cruise",
    color = "Particle\nNumber"
  ) +
  guides(color = guide_legend(ncol = 2)) +
  facet_wrap(~cruise, ncol = 2) +
  coord_sf(expand = FALSE))
plt_within

if (FALSE) {
  # create image file
  png(
    here(plot_out_path, "particles_within_fknms.png"),
    width  = 3000,
    height = 2000,
    res    = 300,
    type   = "cairo"
    ) 

  print(plt_within)
  dev.off()
  }

plotly::ggplotly(plt_within)
```


```{r}
within_part <- 
  within_fk_bind %>% 
  distinct(cruise, part_id, part_num) 

within_part_count <- count(within_part, cruise, part_id)

within_all <- 
  particle_track_paths %>% 
  str_subset(paste(unique(within_part$cruise), collapse = "|")) %>% 
  map2(
    ., 
    tidyr::nest(within_part, .by = cruise)$data,
    \(.x, .y) {
      particle_track <- readr::read_csv(.x, show_col_types = FALSE) %>% 
        filter(
          part_id %in% .y$part_id,
          part_num %in% .y$part_num
        )
      }
  ) %>% 
  set_names(unique(within_part$cruise)) %>% 
  list_rbind(names_to = "cruise")

if (FALSE) {
  
  list(
    "within_fknms" = as_tibble(within_fk_bind) %>% 
                     mutate(
                       lon = st_coordinates(geometry)[, "X"],
                       lat = st_coordinates(geometry)[, "Y"]
                     ) %>% 
                     select(-geometry),
    "particles"    = within_part,
    "count"        = within_part_count,
    "full_path"    = select(within_all, -geometry)
    ) %>% 
  writexl::write_xlsx(here(plot_out_path, "particles_within_fknms.xlsx"))
}

```



```{r}
within_all2 <- 
  arrange(within_all, cruise, part_id, part_num, time) %>% 
  mutate(
    .by = c(cruise, part_id, part_num),
    part_num = as.character(part_num),
    lon_lead = lead(lon, default = last(lon)),
    lat_lead = lead(lat, default = last(lat))
  )

within_all2
```


```{r}
# shelf(ggarchery)
within_arrows <- 
  base_plt +
  geom_sf(data = fknms_south, fill = NA, color = "red") +
  ggarchery::geom_arrowsegment(
    data = within_all2,
    aes(
      x = lon,
      y = lat,
      xend = lon_lead,
      yend = lat_lead,
      color = part_num
    ),
    linewidth = rel(0.2),
    arrow_positions = 0.5,
    arrows = arrow(length = unit(0.01, "inches")),
    na.rm = TRUE
  ) +
  geom_point(
    data = filter(within_all2, .by = cruise, time == first(time)) %>%
      distinct(cruise, lat, lon),
    aes(x = lon, y = lat),
    color = "black",
    # fill = "black",
    alpha = 0.5,
    shape = 20
  ) + 
  # geom_segment(
  #   data = arrange(within_all, cruise, part_id, part_num, time),
  #   aes(x = lon, y = lat, color = part_num)
  # ) +
  # geom_sf(
  #   data = st_as_sf(within_all, coords = c("lon", "lat"), crs = "EPSG:4326"),
  #   aes(color = as.character(part_num), group = cruise),
  #   size = rel(0.5)
  #   ) +
  labs(
    shape = "Cruise",
    color = "Particle\nNumber"
  ) +
  guides(color = guide_legend(ncol = 2)) +
  facet_wrap(~cruise, ncol = 2) +
  coord_sf(
    xlim = c(-83.3, -79.75),
    ylim = c(24.2, 25.7),
    expand = FALSE
    )



# within_arrows
if (FALSE) {
 # create image file
  png(
    here(plot_out_path, "particles_within_fknms_arrow.png"),
    width  = 3000 * 2,
    height = 2000 * 2,
    res    = 300,
    type   = "cairo"
    )

  print(within_arrows)

  dev.off()
} else {
    print(within_arrows)
  }
```

```{r}
cruise_fk <- 
  distinct(within_fk_bind, cruise) %>% 
  pull(cruise)


within_fk <- 
  str_subset(particle_track_paths, paste(cruise_fk, collapse = "|")) %>% 
  map(
    ., 
    \(.x) {
      particle_track <- readr::read_csv(.x, show_col_types = FALSE)
      
      within_fk <-
        particle_track %>%
        st_as_sf(coords = c("lon", "lat"), crs = "EPSG:4326", remove = FALSE) %>% 
         mutate(
           .before = 1,
           cruise = basename(.x),
           cruise = str_remove(cruise, "_.*")
           ) 
      }
  )

within_fk_bind <- 
  list_rbind(within_fk) %>% 
  st_as_sf() %>%
  arrange(cruise, part_id, part_num, time) %>% 
  # filter(part_id == "a" & part_num %in% 1:5) %>% 
  mutate(
    .by = c(cruise, part_id, part_num),
    part_num = as.character(part_num),
    lon_lead = lead(lon, default = last(lon)),
    lat_lead = lead(lat, default = last(lat))
  )
within_fk_bind

first_day <- 
  within_fk_bind %>% 
  filter(
    .by = cruise,
    time == first(time)
  ) %>%
  distinct(time) %>% 
  mutate(time2 = time + days(7)) %$%
  map2(
    time,
    time2,
    \(t1, t2) {
      seq.POSIXt(t1, t2, "hour")
    }
  ) %>% 
  list_c()

face_label <- 
  within_fk_bind %>% 
  as_tibble() %>% 
  distinct(cruise, time) %>% 
  mutate(
    .by   = cruise, 
    first = as_date(first(time)),
    last  = as_date(last(time)),
    first = format(first, "%b %d %Y"),
    last  = format(last,  "%b %d %Y"),
  ) %>% 
  distinct(cruise, first, last) %>% 
  mutate(
    face_label = glue::glue("{cruise} ({first} - {last})")
  ) %>%
  select(-2, -3)

within_fk_bind <- 
  within_fk_bind %>% 
  left_join(
    face_label,
    by = "cruise"
  )

within_fk_bind_7d <- within_fk_bind %>% 
  filter(
    time %in% first_day
    # between(time, first_day$time, first_day$time2)
  )


```


```{r}
particle_arrow <- 
  base_plt +
  geom_sf(data = fknms_south, fill = NA, color = "red") +
  ggarchery::geom_arrowsegment(
    data = filter(within_fk_bind, cruise != "WS17282"),
    # data = within_fk_bind,
    # data = within_fk_bind_7d,
    aes(
      x = lon,
      y = lat,
      xend = lon_lead,
      yend = lat_lead,
      # color = part_num # each particle
      group = part_num, # each particle
      color = part_id # starting location
    ),
    linewidth = rel(0.2),
    arrow_positions = 0.5,
    arrows = arrow(length = unit(0.01, "inches")),
    na.rm = TRUE,
    key_glyph = "point"
    # show.legend = FALSE
  ) +
  geom_point(
    # data = filter(within_fk_bind, .by = cruise, time == first(time)) %>%
    data = filter(within_fk_bind_7d, .by = cruise, time == first(time)) %>%
      distinct(cruise, lat, lon, part_id),
    aes(x = lon, 
        y = lat, 
        fill = part_id # starting location
        ),
    color = "black",
    # fill = "black",
    alpha = 0.8,
    size = rel(5),
    shape = 21,
    stroke = rel(1.2),
    show.legend = FALSE
  ) + 
  # geom_segment(
  #   data = arrange(within_all, cruise, part_id, part_num, time),
  #   aes(x = lon, y = lat, color = part_num)
  # ) +
  # geom_sf(
  #   data = st_as_sf(within_all, coords = c("lon", "lat"), crs = "EPSG:4326"),
  #   aes(color = as.character(part_num), group = cruise),
  #   size = rel(0.5)
  #   ) +
  labs(
    shape = "Cruise",
    color = NULL
    # color = "Particle\nNumber"
  ) +
  scale_color_manual(
    values = c("#E69F00", "#56B4E9", "#009E73"),
    labels = c("Everglades", "West Florida Bay", "East Florida Bay")
    ) +
  scale_fill_manual(
    values = c("#E69F00", "#56B4E9", "#009E73"),
    labels = c("Everglades", "West Florida Bay", "East Florida Bay")
    ) +
  guides(color = guide_legend(ncol = 3, override.aes = list(size = rel(3)))) +
  # facet_wrap(~cruise, ncol = 2) +
  # facet_wrap(~face_label, ncol = 2) +
  facet_wrap(~face_label, ncol = 1) +
  coord_sf(
    xlim = c(-83.3, -79.75),
    ylim = c(24.2, 25.7),
    expand = FALSE
    ) +
  theme(
    strip.text = element_text(size = rel(2)),
    axis.text = element_text(size = rel(1.5)),
    legend.position = "bottom",
    legend.text = element_text(size = rel(2))
  )

# within_arrows
if (T) {
 # create image file
  png(
    here(plot_out_path, "full_particles_arrow.png"),
    width  = 3500,
    height = 2000 * 2,
    res    = 300,
    type   = "cairo"
    )

  print(particle_arrow)

  dev.off()
} else {
  print(particle_arrow)
    
  }



```

